camara/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^camaras_list/$', views.camara_list, name='listar_camaras'),
    url(r'^camara_delete/(?P<camara_name>.*)$', views.camara_delete, name='camara_delete'),
    url(r'^generate_pdf/$', views.generate_pdf, name='generate_pdf'),
    url(r'^camaras_list_for_reports/$', views.get_all_boxes, name='listar_camaras_relatorios'),
    url(r'^all_camaras_reports/$', views.get_all_boxes, name='relatorio_geral'),
    url(r'^transports_list_for_reports/(?P<camara_name>.*)$', views.get_transports_from_box, name='listar_transports_relatorios'),
    #  url(r'^reports_list/(?P<camara_name>.*)/(?P<transport_id>[0-9]+)$', views.reports_list, name='reports_list'),
    url(r'^camaras_cadastro/$', views.camara_list, name='camaras_cadastro')
]

transportadora_orgaos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from usuario.views import Index
from camara.views import camara_list

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', camara_list, name='home'),
    url(r'^', include('usuario.urls', namespace='usuario', app_name='usuario')),
    url(r'^', include('camara.urls', namespace='camara', app_name='camara')),
    url(r'^', include('transport.urls', namespace='transport', app_name='transport'))
]

usuario/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cadastro$', views.cadastro, name='cadastro'),
    url(r'^login$', views.do_login, name='login'),
    url(r'^logout$', views.do_logout, name='logout'),
    url(r'^list$', views.list, name='list'),
    url(r'^denied$', views.denied, name='denied'),
    url(r'^user_delete/(?P<users_username>.*)$', views.del_User, name='user_delete')
]

usuario/models.py
from __future__ import unicode_literals
from django.db import models

class Usuario(models.Model):
	
    username = models.CharField(max_length = 50, null=False)
    password = models.CharField(max_length = 50, null=False)
    email = models.CharField(max_length=50, null=False)
    access_level = models.CharField(max_length=15, null=False)
	
    def __unicode__(self):
        return "{} - {}".format(self.id,self.name)

usuario/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from usuario.models import Usuario

class UsuarioModelForm(ModelForm):
    ADMINISTRADOR = "Administrador"
    TRASPORTADOR = "Transportador"
    USUARIO = "Usuario"
    ACCESS_CHOICES = (
    (ADMINISTRADOR, 'Administrador'), 
    (TRASPORTADOR, 'Transportador'),
    (USUARIO, 'Usuário'),
    )
    access_level = forms.ChoiceField(choices= ACCESS_CHOICES)

    class Meta:
        model = Usuario
        fields = ['username', 'password', 'email', 'access_level']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form_control', 'maxlength': 50}),
            'email': forms.TextInput(attrs={'class': 'form_control', 'maxlength': 50}),
            'password': forms.PasswordInput(attrs={'class': 'form_control', 'maxlength': 50})
        }

class UsuarioLoginForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form_control', 'maxlength': 50}),
            'email': forms.TextInput(attrs={'class': 'form_control', 'maxlength': 50}),
        }

usuario/views.py
from django.shortcuts import render, render_to_response, redirect
from usuario.forms import UsuarioModelForm, UsuarioLoginForm
from django.views.generic import TemplateView
import requests
import json


class Index(TemplateView):
    template_name = 'base.html'

def recupera_token(request):
    #RECUPERAR O NOVO TOKEN DA API
    headers = {'content-type': 'application/json'}
    url = "https://transports-rest-api.herokuapp.com/auth"
    payload = "{\n\t\"username\": \""+ request.session['username'] +"\",\n\t\"password\": \""+ request.session['password'] +"\"\n}"
    request.session['token'] = requests.post(url, data=payload, headers=headers).json()


def cadastro(request, template_name='usuario/cadastro.html'):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            form = UsuarioModelForm(request.POST or None)
			
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                email = form.cleaned_data['email']
                access_level = form.cleaned_data['access_level']

                headers = {'content-type': 'application/json'}
                payload = "{\n\t\"username\": \""+ username +"\",\n\t\"password\": \""+ password +"\", \n\t\"email\": \""+ email +"\", \n\t\"access_level\": \""+ access_level +"\"\n}"
                url = "https://transports-rest-api.herokuapp.com/user"
                
                
                response = requests.post(url, data=payload, headers=headers)


                if 'error_message' in response.json():
                    response_dict = response.json()
                    return render(request, template_name, {'form': form, 'response_dict': response_dict})
                else:
                    return redirect('usuario:list')
            return render(request, template_name, {'form': form})
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def do_login(request, template_name='usuario/login.html'):
    form = UsuarioLoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        headers = {'content-type': 'application/json'}
        payload = "{\n\t\"username\": \""+ username +"\",\n\t\"password\": \""+ password +"\"\n}"
        url = "https://transports-rest-api.herokuapp.com/auth"
        response = requests.post(url, data=payload, headers=headers)

        if 'error' in response.json():
            response_dict = response.json()
            response_dict['error'] = "Usuario e/ou Senha invalidos"
            return render(request, template_name, {'form': form, 'response_dict': response_dict})
        elif 'access_token' in response.json():
            token = response.json()
            request.session['token'] = token
            request.session['username'] = username
            request.session['password'] = password
            access_level = get_acess_level(request)
            request.session['access_level'] = access_level['access_level']
            return redirect('home')
    return render(request, template_name, {'form': form})

def formView(request):
    if request.session.has_key('token'):
        recupera_token(request)
        token = request.session['token']
        return render(request, 'home', {"token" : token})
    else:
        return render(request, 'usuario/login.html', {})

def do_logout(request):
    try:
        del request.session['token']
    except:
        pass
    return redirect('usuario:login')

def list(request, template_name='usuario/list.html'):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            url = "https://transports-rest-api.herokuapp.com/users"
            headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}
            
           
            users = requests.request("GET", url, headers=headers)
           
            users_dict = users.json()['users']

            return render(request, template_name, {'users_dict':users_dict})
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def del_User(request, users_username, template_name='usuario/list.html'):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}
            payload = "{\n\t\"username\": \""+ users_username +"\"\n}"
            url = "https://transports-rest-api.herokuapp.com/user"

            
            response = requests.request("DELETE", url, data=payload, headers=headers)
            

            return redirect('usuario:list')
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def get_acess_level(request):

    url = "https://transports-rest-api.herokuapp.com/user_access/" + request.session['username']
    headers = {'content-type': 'application/json'}
    response = requests.request("GET", url, headers=headers)

    if 'access_level' in response.json():
        level = response.json()

    return level

def denied(request):
    template_name = 'denied.html'
    return render(request, template_name)

templates/usuario/cadastro.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
	<div class="row">
		<div class="col-md-12">
			<h2 class="form-sign-heading"><strong>Cadastro de Usuário</strong></h2>
		</div>
	</div>
	<div class="row">
        <div class="col-md-12">
            <div class="card card-cadastro">
                <div class="card-body">
                    <h3 class="title-modules-report"><strong>Novo Usuário</strong></h3>
                    <form action="{% url 'usuario:cadastro' %}" class="form-sign" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Nome de Usuário: </label>
                                    {{ form.username }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email: </label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Senha: </label>
                                    {{ form.password }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
									<label>Nível de Acesso: </label>
								        {{ form.access_level }}
							    </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <button class="btn btn-outline-primary btn-block" type="submit">Registrar</button>
                                </div>
                            </div>
                            <span class="error-message">{{ response_dict.error_message }}</span>
                        </div>
                    </form>
                </div>
			</div>
        </div>
    </div>
</div>
{% endblock %}

templates/usuario/list.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
	<div class="row">
            <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <a href="{% url 'usuario:cadastro' %}"><button class="btn btn-outline-primary btn-cadastrar-camara pull-right-xs">Cadastrar novo usuário</button></a>
                            <h2 class="form-sign-heading">Lista de Usuário</h2>
                                
                        </div>
                        
                        {% if not users_dict %}
                            <p> Nenhum usuário cadastrado </p>
                        {% endif %}
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped" size="14">
                                    <thead>
                                        <tr>
                                            <th style="font-size: 15px">Nome</th>
                                            <th style="font-size: 15px">Email</th>
                                            <th style="font-size: 15px">Nível de Acesso</th>
                                            <th style="font-size: 15px">Apagar?</th>
                                        </tr>
                                    </thead>
                        			{% for users in users_dict %}
                                    <tbody>
                                        <tr>
                                            <td style="font-size: 13px">{{users.username}}</td>
                                            <td style="font-size: 13px">{{users.email}}</td>
                                            <td style="font-size: 13px">{{users.access_level}}</td>
                                            <td style="font-size: 13px"><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#{{forloop.counter}}">Deletar Usuário</button> </td>
                                            {% include "usuario/modal/del_user.html" %}
                                        </tr>

                                    </tbody>
                   					{% endfor %}
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
	</div>

{% endblock %}

templates/usuario/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TransOrg - Sistema de Trasporte de Órgãos para Transplante</title>

    <link href="{% static "css/main.css" %}" rel="stylesheet">

    <!-- Bootstrap Core CSS -->
    <link href="{% static "bootstrap/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <link href="{% static "mdb/css/mdb.min.css" %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static "bootstrap/vendor/metisMenu/metisMenu.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "bootstrap/dist/css/sb-admin-2.css" %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static "bootstrap/vendor/morrisjs/morris.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "bootstrap/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{% static "js/google-charts.js" %}"></script>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'camara:listar_camaras' %}"><span class="brand-part-1">TRANS</span><span class="brand-part-2">ORG</span></a>
            </div>
            <!-- /.navbar-header -->
        </nav>

    </div>
{% block conteudo %}
<div id="container">
	<div class="row">
            <div class="col-md-4 col-sm-6 col-xs-10 col-md-offset-4 col-sm-offset-3 col-xs-offset-1">
                <div class="card card-login" style="margin-top: 60px;">
                    <h2 class="card-title title-modules-report"><strong>Login</strong></h2>
					<form class="form-sign" method="POST">
						{% csrf_token %}
					<div class="card-body">
						{% if form.errors %}
                            <p><strong>Usuário e/ou senha inválidos.</strong></p>
                        {% endif %}
                            <fieldset>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nome de Usuário: </label>
										<input type="text" name="username" class="form-control">
								    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
										<label>Senha: </label>
										<input type="password" name="password" class="form-control">
								    </div>
                                </div>

                                <span class="error-message">{{ response_dict.error }}</span>

                                <div class="col-lg-12">
                                    <div class="form-group">
										<button class="btn btn-outline-primary btn-block" type="submit">Login</button>
                                    </div>
                                </div>
                                  
                            </fieldset>
                    </div>
					</form>
				</div>
			</div>
	</div>
{% endblock %}

    <!-- jQuery -->
    <script src="{% static "bootstrap/vendor/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "bootstrap/vendor/bootstrap/js/bootstrap.min.js" %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static "bootstrap/vendor/metisMenu/metisMenu.min.js" %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static "bootstrap/vendor/raphael/raphael.min.js" %}"></script>
    <script src="{% static "bootstrap/vendor/morrisjs/morris.min.js" %}"></script>
    <script src="{% static "bootstrap/data/morris-data.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "bootstrap/dist/js/sb-admin-2.js" %}"></script>

</body>

</html>