camara/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^camaras_list/$', views.camara_list, name='listar_camaras'),
    url(r'^camara_delete/(?P<camara_name>.*)$', views.camara_delete, name='camara_delete'),
    url(r'^generate_pdf/$', views.generate_pdf, name='generate_pdf'),
    url(r'^camaras_list_for_reports/$', views.get_all_boxes, name='listar_camaras_relatorios'),
    url(r'^all_camaras_reports/$', views.get_all_boxes, name='relatorio_geral'),
    url(r'^transports_list_for_reports/(?P<camara_name>.*)$', views.get_transports_from_box, name='listar_transports_relatorios'),
    #  url(r'^reports_list/(?P<camara_name>.*)/(?P<transport_id>[0-9]+)$', views.reports_list, name='reports_list'),
    url(r'^camaras_cadastro/$', views.camara_list, name='camaras_cadastro')
]

transportadora_orgaos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from usuario.views import Index
from camara.views import camara_list

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', camara_list, name='home'),
    url(r'^', include('usuario.urls', namespace='usuario', app_name='usuario')),
    url(r'^', include('camara.urls', namespace='camara', app_name='camara')),
    url(r'^', include('transport.urls', namespace='transport', app_name='transport'))
]

camara/models.py
from __future__ import unicode_literals
from django.db import models


class Camara(models.Model):
 name = models.CharField(max_length = 50, null=False)

camara/views.py
# -*-encoding: utf-8 -*-

from django.forms import ModelForm
from .models import *
from django.shortcuts import render, redirect
import requests
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
from usuario.views import get_acess_level

from weasyprint import HTML

class CamaraForm(ModelForm):
    class Meta:
        model = Camara
        fields = ['name']

def recupera_token(request):
    #RECUPERAR O NOVO TOKEN DA API
    headers = {'content-type': 'application/json'}
    url = "https://transports-rest-api.herokuapp.com/auth"
    payload = "{\n\t\"username\": \""+ request.session['username'] +"\",\n\t\"password\": \""+ request.session['password'] +"\"\n}"
    request.session['token'] = requests.post(url, data=payload, headers=headers).json()

def camara_list(request, template_name='page_camaras_list.html'):

    if 'token' in request.session:
        recupera_token(request)

        url = "https://transports-rest-api.herokuapp.com/boxes"
        headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}
        payload = ""

        camaras = requests.request("GET", url, headers=headers)
        camaras_dict = camaras.json()['boxes']
        
        form = CamaraForm(request.POST or None)

        if form.is_valid():
            url = "https://transports-rest-api.herokuapp.com/box/" + form.cleaned_data['name']
            response = requests.post(url, data=payload, headers=headers)
        
            if 'error_message' in response.json():
                response_dict = response.json()
                return render(request, template_name, {'form': form, 'response_dict': response_dict, 'camaras_dict':camaras_dict})
            else:
                return redirect('camara:listar_camaras')
        return render(request, template_name, {'camaras_dict':camaras_dict, 'form':form})
    else:
        return redirect('usuario:login')


def camara_delete(request, camara_name, template_name="page_camaras_list.html"):

    recupera_token(request)
    	
    payload = ""
    headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}

    #Deletar câmara específica
    url = "https://transports-rest-api.herokuapp.com/box/" + camara_name
    response = requests.request("DELETE", url, data=payload, headers=headers)

    return redirect('camara:listar_camaras')

def get_all_boxes(request, template_name='all_camaras_reports.html'):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            url = "https://transports-rest-api.herokuapp.com/boxes"
            headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}

            
            camaras = requests.request("GET", url, headers=headers)
            
            
            camaras_dict = camaras.json()['boxes']
            return render(request, template_name, {'camaras_dict':camaras_dict})
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def get_transports_from_box(request, camara_name, template_name="transports_list_for_reports.html"):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            url = "https://transports-rest-api.herokuapp.com/box/" + camara_name
            headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}
            
            
            camara_transports = requests.request("GET", url, headers=headers).json()['transports']
            

            return render(request, template_name, {'camara_transports' : camara_transports})
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def generate_pdf(request):
    recupera_token(request)
    url = "https://transports-rest-api.herokuapp.com/boxes"
    headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}

    camaras = requests.request("GET", url, headers=headers)
    camaras_dict = camaras.json()['boxes']

    
    
    html_string = render_to_string(
        'pdf_template.html', {'camaras_dict': camaras_dict})

    html = HTML(string=html_string)
    html.write_pdf(target='/tmp/reports.pdf')

    fs = FileSystemStorage('/tmp')
    with fs.open('reports.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="reports.pdf"'
        return response

    return response

camara/templates/all_camaras_reports.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'camara:generate_pdf' %}" class="btn btn-primary pull-left">PDF</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-body">
                <!-- {% if not camaras_dict %}
                    <span class="error-message"> Nenhuma câmara cadastrada </span>
                {% endif %} -->
                <div class="row">
                    <div class="container">
                        {% for camara in camaras_dict %}
                            <h1>{{camara.name}}</h1>
                            {% for transport in camara.transports %}
                                <b>Responsável: {{transport.responsible}}</b><br>
                                <b>Órgão: {{transport.organ}}</b> <br>                               
                                {% for report in transport.reports %}
                                    <table class="table">
                                        <thead>
                                            <th>Data</th>
                                            <th>Temperatura</th>
                                            <th>Latitude</th>
                                            <th>Longitude</th>
                                            <th>Estava Trancada?</th>
                                        </thead>
                                        <tbody>
                                            <td>{{report.date}}</td>
                                            <td>{{report.temperature}}</td>
                                            <td>{{report.latitude}}</td>
                                            <td>{{report.longitude}}</td>
                                             {% if report.is_locked == 1 %}
                                            <td>Sim</td>
                                            {% else %}
                                            <td>Não</td>
                                            {% endif %}
                                        </tbody>
                                    </table>
                                {% endfor %}
                            {% endfor %}
                        {% endfor %}
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

 

camara/templates/all_reports_list.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2>Relatório - Câmara {{camara.id}} - Tranporte {{transport.id}}</h2>
            <a href="{% url 'camara:generate_pdf' %}" class="btn btn-primary pull-right">PDF</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-body">
                {% if not camaras_dict %}
                    <span class="error-message"> Nenhuma câmara cadastrada </span>
                {% endif %}
                <div class="row">
                
                    <div class="container">
                            
                            <table class="table">
                            <thead> 
                                <tr>
                                    <th>Nome</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for camara in camaras_dict %}
                                <tr> 
                                    <td>{{camara.name}}</td>
                                    {% for transport in camara.transports%}
                                    <tr>
                                        <th>{{transport.responsible}}</th>
                                        <tr>
                                            <th>{{transport.organ}}</th>
                                        </tr>
                                    </tr>  
                                    {% for report in transport.reports %}
                                    <tr>
                                            <tr>
                                                <th>{{report.temperature}}</th>
                                                <th>{{report.latitude}}</th>
                                                <th>{{report.longitude}}</th>
                                                <th>{{report.is_locked}}</th>
                                                <th>{{report.date}}</th>
                                            </tr>
                                        </tr>  
                                </tr>
                                        {% endfor %}
                                        {% endfor%}
                                {% endfor %}
                            </tbody>
                            </table>
                           
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

camara/templates/camaras_list_for_reports.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2>Câmaras Cadastradas</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-body">
                {% if not camaras_dict %}
                    <span class="error-message"> Nenhuma câmara cadastrada </span>
                {% endif %}
                <div class="row">
                
                    <div class="container">
                            
                            <table class="table">
                            <thead> 
                                <tr>
                                    <th>Nome da Câmara</th>
                                    <th><span class="pull-right">Ações</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for camara in camaras_dict %}
                                <tr>
                                    <td><a> {{camara.id}} - {{camara.name}}</a></td>
                                    <td>
                                        <a href="{% url 'camara:listar_transports_relatorios' camara.name %}" class="btn btn-primary pull-right">Visualizar Transportes</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                           
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

camara/templates/page_camaras_list.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
    <div class="row">
        <div class="hidden-xxs hidden-xs hidden-sm col-md-8">
            <h1><strong>Câmaras</strong></h1>
        </div>

        {% if request.session.access_level == "Administrador" %}
        <div class="col-sm-8 col-md-4">
            <button class="btn btn-outline-primary btn-cadastrar-camara pull-right-xs" data-toggle="modal" data-target="#cadastro_camara">Cadastrar nova câmara</button>
        </div>   
    </div>
    <div class="row">
        {% include "modals/cadastro_camara.html" %}
        {% endif %}
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-body">
                {% if not camaras_dict %}
                    <div class="alert alert-danger">
                    Nenhuma câmara cadastrada
                    </div>  
                {% endif %}
                <div class="row">
                {% if request.session.access_level == "Administrador" or request.session.access_level == "Transportador" %}
                {% for camara in camaras_dict %}
                    <div class="col-md-4">
                        <div class="card card-camara card-height-camara">
                            <div class="card-body">
                                <center>
                                    <h2 id="camara-name" class="card-title title-modules-report"><strong>{{camara.name}}</strong></h2>
                                    {% if not camara.transports %}
                                        <!--  DISPONIVEL -->
                                        {% include "modules/module_box_available.html" %}
                                        {% include "modals/delete_camara.html" %}
                                        
                                    {% else %}
                                        {% with camara.transports|last as last_transport %}
                                        {% with last_transport.reports|last as last_report %}
                                            {% if not last_transport.reports %}
                                            <!--  AGUARDANDO CONEXAO -->
                                            {% include "modules/module_box_waiting.html" %}
                                            
                                            {% else %}
                                                {% if last_report.enable == 0 %}
                                                <!--  DISPONIVEL -->
                                                {% include "modules/module_box_available.html" %}
                                                {% include "modals/delete_camara.html" %}
                                                
                                                {%  elif last_report.enable == 1 %}
                                                <!-- EM USO -->
                                                {% include "modules/module_box_use.html" %}
                                                
                                                {% endif %}
                                                
                                            {% endif %}
                                        {% endwith %}
                                        {% endwith %}
                                    {% endif %}
                                </center>
                            </div>
                        </div>
                    </div> 
                {% endfor %}

                {% else %}
                    {% for camara in camaras_dict %}
                        {% with camara.transports|last as last_transport %}
                        {% with last_transport.reports|last as last_report %}
                        {%  if last_report.enable == 1 %}
                        <div class="col-md-4">
                            <div class="card card-height-camara">
                                <div class="card-body">
                                    <center>
                                        <h2 id="camara-name" class="card-title title-modules-report"><strong>{{camara.name}}</strong></h2>
                                        
                                        <!-- EM USO -->
                                        {% include "modules/module_box_use.html" %}
                                    </center>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% endwith %}
                        {% endwith %}
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

camara/templates/pdf_template.html
{% block conteudo %}
<html>
<head>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 5px;
            text-align: left;
        }
    </style>
</head>
<body>
    {% for camara in camaras_dict %}
        <h1>{{camara.name}}</h1>
        {% for transport in camara.transports %}
            <h3>Responsável: {{transport.responsible}}</h3>
            <h3>Órgão: {{transport.organ}}</h3>
            {% for report in transport.reports %} 
            <table style="width:100%">
                <tr>
                    <th>Data</th>
                    <td>{{report.date}}</td>
                </tr>
                <tr>
                    <th>Latitude</th>
                    <td>{{report.latitude}}</td>
                </tr>
                <tr>
                    <th>Longitude</th>
                    <td>{{report.longitude}}</td>
                </tr>
                <tr>
                    <th>Temperatura</th>
                    <td>{{report.temperature}}</td>
                </tr>
                <tr>
                    <th>Estava Trancada?</th>
                    {% if report.is_locked == 1 %}
                        <td>Sim</td>
                    {% else %}
                        <td>Não</td>
                    {% endif %}
                </tr>
            </table>
            <br>
            {% endfor %}
        {% endfor %}
     {% endfor %}
</body>
</html>
{% endblock %}

camara/templates/reports_list.html
{% extends 'base.html' %}
{% block conteudo %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h2>Relatório - Câmara {{camara.id}} - Tranporte {{transport.id}}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-body">
                {% if not reports_dict %}
                    <span class="error-message"> Nenhuma câmara cadastrada </span>
                {% endif %}
                <div class="row">
                
                    <div class="container">
                            
                            <table class="table">
                            <thead> 
                                <tr>
                                    <th>Data</th>
                                    <th>Latitude</th>
                                    <th>Longitude</th>
                                    <th>Temperatura</th>
                                    <th>Está Trancada?</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for report in reports_dict %}
                                <tr>
                                    <td>{{report.date}}</td>
                                    <td>{{report.latitude}} </td>
                                    <td>{{report.longitude}}</td>
                                    <td>{{report.temperature}}</td>
                                    <td>{{report.is_locked}}</td>                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                           
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}