camara/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^camaras_list/$', views.camara_list, name='listar_camaras'),
    url(r'^camara_delete/(?P<camara_name>.*)$', views.camara_delete, name='camara_delete'),
    url(r'^generate_pdf/$', views.generate_pdf, name='generate_pdf'),
    url(r'^camaras_list_for_reports/$', views.get_all_boxes, name='listar_camaras_relatorios'),
    url(r'^all_camaras_reports/$', views.get_all_boxes, name='relatorio_geral'),
    url(r'^transports_list_for_reports/(?P<camara_name>.*)$', views.get_transports_from_box, name='listar_transports_relatorios'),
    #  url(r'^reports_list/(?P<camara_name>.*)/(?P<transport_id>[0-9]+)$', views.reports_list, name='reports_list'),
    url(r'^camaras_cadastro/$', views.camara_list, name='camaras_cadastro')
]

transportadora_orgaos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from usuario.views import Index
from camara.views import camara_list

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', camara_list, name='home'),
    url(r'^', include('usuario.urls', namespace='usuario', app_name='usuario')),
    url(r'^', include('camara.urls', namespace='camara', app_name='camara')),
    url(r'^', include('transport.urls', namespace='transport', app_name='transport'))
]

usuario/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cadastro$', views.cadastro, name='cadastro'),
    url(r'^login$', views.do_login, name='login'),
    url(r'^logout$', views.do_logout, name='logout'),
    url(r'^list$', views.list, name='list'),
    url(r'^denied$', views.denied, name='denied'),
    url(r'^user_delete/(?P<users_username>.*)$', views.del_User, name='user_delete')
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />

        <title>TransOrg - Sistema de Trasporte de Órgãos para Transplante</title>

        <!-- Styles applied -->
        <link href="{% static "css/main.css" %}" rel="stylesheet">
        <link href="{% static "bootstrap/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "mdb/css/mdb.min.css" %}" rel="stylesheet">
        <link href="{% static "bootstrap/dist/css/sb-admin-2.css" %}" rel="stylesheet">

        
        

        <!-- Font Awesome -->
        <link href="{% static "bootstrap/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
        
    </head>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'camara:listar_camaras' %}"><span class="brand-part-1">TRANS</span><span class="brand-part-2">ORG</span></a>
                </div>
                <!-- /.navbar-header -->
                <ul class="nav navbar-top-links navbar-right hidden-xs">
                    <li><a href="{% url 'usuario:logout' %}" class="text-sidebar">Sair <i class="fa fa-sign-out fa-fw"></i></a></li>
                    
                </ul>
                <!-- /.navbar-top-links -->

                    {% if request.session.access_level == "Administrador"%}
                    <div class="navbar-default sidebar" role="navigation">
                        <div class="sidebar-nav navbar-collapse collapse">
                            <ul class="nav" id="side-menu">
                                <li>
                                    <a href="{% url 'camara:listar_camaras' %}"><i class="fa fa-ambulance fa-2x fa-fw fa-side-bar"></i> <span class="text-sidebar">Todas as Câmaras</span></a>
                                </li>
                                <li>
                                    <a href="{% url 'usuario:list' %}"><i class="fa fa-user fa-2x fa-fw fa-side-bar"></i> <span class="text-sidebar">Usuários</span></a>
                                </li>
                                <li>
                                    <a href="{% url 'camara:relatorio_geral' %}"><i class="fa fa-file-pdf-o fa-2x fa-fw"></i> <span class="text-sidebar">Gerar Relatórios</span></a>
                                </li>
                                <li class="hidden-sm hidden-md hidden-lg">
                                    <a href="{% url 'usuario:logout' %}" class="text-sidebar"><i class="fa fa-sign-out fa-2x fa-fw"></i> Sair</a>
                                </li>
                                
                            </ul>
                        </div>
                        <!-- /.sidebar-collapse -->
                    </div>
                    {% endif %}
                <!-- /.navbar-static-side -->
            </nav>

        </div>
       
         <script type="text/javascript" src="{% static "js/api.js" %}"></script>
         <!-- jQuery -->
         <script src="{% static "bootstrap/vendor/jquery/jquery.min.js" %}"></script>

          <!-- Google Maps Scripts -->
        <script type="text/javascript" src="{% static "js/google-maps.js" %}"></script>
       
        <!-- Content Block -->
        {% block conteudo %}
        <div id="page-wrapper">
                
        </div>
        {% endblock %}

        

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static "bootstrap/vendor/bootstrap/js/bootstrap.min.js" %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static "bootstrap/dist/js/sb-admin-2.js" %}"></script>

         <!-- JavaScript Base -->
         <script src="{% static "js/main.js" %}"></script>

        <!-- Google Charts Scripts -->
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript" src="{% static "js/google-chart-line.js" %}"></script>
        <script type="text/javascript" src="{% static "js/google-chart-gauge.js" %}"></script> 
        <script type="text/javascript" src="{% static "js/report-information.js" %}"></script>
        <script type="text/javascript" src="{% static "js/refresh.js" %}"></script>
        
    </body>
</html>

templates/denied.html
{% extends 'base.html' %}
{% block conteudo %}

<div id="page-wrapper">
	<div class="row">
		<div class="col-md-12">
			<h2 class="form-sign-heading"><strong>Acesso Negado</strong></h2>
		</div>
	</div>
</div>
{% endblock %}