camara/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^camaras_list/$', views.camara_list, name='listar_camaras'),
    url(r'^camara_delete/(?P<camara_name>.*)$', views.camara_delete, name='camara_delete'),
    url(r'^generate_pdf/$', views.generate_pdf, name='generate_pdf'),
    url(r'^camaras_list_for_reports/$', views.get_all_boxes, name='listar_camaras_relatorios'),
    url(r'^all_camaras_reports/$', views.get_all_boxes, name='relatorio_geral'),
    url(r'^transports_list_for_reports/(?P<camara_name>.*)$', views.get_transports_from_box, name='listar_transports_relatorios'),
    #  url(r'^reports_list/(?P<camara_name>.*)/(?P<transport_id>[0-9]+)$', views.reports_list, name='reports_list'),
    url(r'^camaras_cadastro/$', views.camara_list, name='camaras_cadastro')
]

transportadora_orgaos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from usuario.views import Index
from camara.views import camara_list

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', camara_list, name='home'),
    url(r'^', include('usuario.urls', namespace='usuario', app_name='usuario')),
    url(r'^', include('camara.urls', namespace='camara', app_name='camara')),
    url(r'^', include('transport.urls', namespace='transport', app_name='transport'))
]

camara/models.py
from __future__ import unicode_literals
from django.db import models


class Camara(models.Model):
 name = models.CharField(max_length = 50, null=False)

camara/views.py
# -*-encoding: utf-8 -*-

from django.forms import ModelForm
from .models import *
from django.shortcuts import render, redirect
import requests
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
from usuario.views import get_acess_level

from weasyprint import HTML

class CamaraForm(ModelForm):
    class Meta:
        model = Camara
        fields = ['name']

def recupera_token(request):
    #RECUPERAR O NOVO TOKEN DA API
    headers = {'content-type': 'application/json'}
    url = "https://transports-rest-api.herokuapp.com/auth"
    payload = "{\n\t\"username\": \""+ request.session['username'] +"\",\n\t\"password\": \""+ request.session['password'] +"\"\n}"
    request.session['token'] = requests.post(url, data=payload, headers=headers).json()

def camara_list(request, template_name='page_camaras_list.html'):

    if 'token' in request.session:
        recupera_token(request)

        url = "https://transports-rest-api.herokuapp.com/boxes"
        headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}
        payload = ""

        camaras = requests.request("GET", url, headers=headers)
        camaras_dict = camaras.json()['boxes']
        
        form = CamaraForm(request.POST or None)

        if form.is_valid():
            url = "https://transports-rest-api.herokuapp.com/box/" + form.cleaned_data['name']
            response = requests.post(url, data=payload, headers=headers)
        
            if 'error_message' in response.json():
                response_dict = response.json()
                return render(request, template_name, {'form': form, 'response_dict': response_dict, 'camaras_dict':camaras_dict})
            else:
                return redirect('camara:listar_camaras')
        return render(request, template_name, {'camaras_dict':camaras_dict, 'form':form})
    else:
        return redirect('usuario:login')


def camara_delete(request, camara_name, template_name="page_camaras_list.html"):

    recupera_token(request)
    	
    payload = ""
    headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}

    #Deletar câmara específica
    url = "https://transports-rest-api.herokuapp.com/box/" + camara_name
    response = requests.request("DELETE", url, data=payload, headers=headers)

    return redirect('camara:listar_camaras')

def get_all_boxes(request, template_name='all_camaras_reports.html'):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            url = "https://transports-rest-api.herokuapp.com/boxes"
            headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}

            
            camaras = requests.request("GET", url, headers=headers)
            
            
            camaras_dict = camaras.json()['boxes']
            return render(request, template_name, {'camaras_dict':camaras_dict})
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def get_transports_from_box(request, camara_name, template_name="transports_list_for_reports.html"):
    if 'token' in request.session:
        recupera_token(request)
        level = get_acess_level(request)
        if 'Administrador' in level["access_level"]:
            url = "https://transports-rest-api.herokuapp.com/box/" + camara_name
            headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}
            
            
            camara_transports = requests.request("GET", url, headers=headers).json()['transports']
            

            return render(request, template_name, {'camara_transports' : camara_transports})
        else:
            return redirect('usuario:denied')
    else:
        return redirect('usuario:login')

def generate_pdf(request):
    recupera_token(request)
    url = "https://transports-rest-api.herokuapp.com/boxes"
    headers = {'content-type': 'application/json', 'authorization': 'jwt ' + request.session['token']['access_token']}

    camaras = requests.request("GET", url, headers=headers)
    camaras_dict = camaras.json()['boxes']

    
    
    html_string = render_to_string(
        'pdf_template.html', {'camaras_dict': camaras_dict})

    html = HTML(string=html_string)
    html.write_pdf(target='/tmp/reports.pdf')

    fs = FileSystemStorage('/tmp')
    with fs.open('reports.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="reports.pdf"'
        return response

    return response

camara/templates/modals/cadastro_camara.html
<div class="modal fade" id="cadastro_camara" role="dialog">
    <div class="modal-dialog">
        
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" {% if response_dict.error_message %} style="display: none;" {% endif %} data-dismiss="modal">&times;</button>
          <h4 class="modal-title">cadastrar nova câmara</h4>
        </div>
        <div class="modal-body">
            <form id="form-cadastrar-camara" class="form-sign" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>nome da câmara: </label>
                                {{ form.name }}
                        </div>
                        {% if response_dict.error_message %}
                            <div class="alert alert-danger">
                                <strong>Já possui uma câmara "{{ form.name.value }}". Escolha outro nome.</strong>
                            </div>
                            
                        {% endif %}
                    <div id="error_message" data-error-message="{{ response_dict.error_message }}"></div>
                    <div class="col-md-4 pull-right">
                        <div class="form-group">
                            <button class="btn btn-outline-primary btn-block" onclick="this.disabled=true; this.form.submit();">Cadastrar</button>
                        </div>
                    </div>
                    {% if response_dict.error_message %}
                        <strong style="font-size: 11px;">Caso queira apenas fechar a caixa de diálogo, entre com um nome vazio</strong>
                    {% endif %} 
                </div>
                
            </form>
        </div>
        
      </div>
      
    </div>
  </div>

camara/templates/modals/delete_camara.html
<div class="modal fade delete-camara" id="{{forloop.counter}}" role="dialog">
  <div class="modal-dialog">
      
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Deletar {{ camara.name }} do sistema?</h4>
      </div>
      <div class="modal-body">
        <p>Isso irá deletar TODOS os transportes e reports associados a essa câmara. Essa ação não pode ser desfeita.</p>
      </div>
      <div class="modal-footer">
        <a href="{% url 'camara:camara_delete' camara.name %}" class="btn btn-danger col-md-12">Deletar</a>
      </div>
    </div>
    
  </div>
</div>